name: runloyal_weblink_v2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: any
  flutter: 
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  url_strategy: ^0.2.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

